### ISSUE TITLE
Missing Key Image

### ISSUE THREAD

**Issue by DrCoffey** [djamesbarker/pMAT#1]
Line 103 references an image from your computer :)

```imshow('D:\Google Drive\Barker Lab\PMAT and Photometry Code\pmat 1-2\BarkerLab.jpg')```

I'm going to need a copy of that image before further testing.

**Comment by djamesbarker** [comment]
Damn. I thought that switched to the dynamic link.

May need to destroy the logo.

**Comment by djamesbarker** [comment]
The logo file is in and the line has been fixed to just imshow the file.

Should work now, provided that the pathtool is run first!

**Comment by goodwinnastacia** [comment]
Was this also updated through the independent deployment exe? I downloaded and ran it ~ 30 minutes ago and am running into the same image issue

**Comment by djamesbarker** [comment]
I am working on this now and will close the issue once I am certain the fix works in both places.

**Comment by djamesbarker** [comment]
The independent deployment should also now reflect the bug fixes. Let me know if this works and I will then close the issue.

This will teach me to be fancy and make last-minute changes :-)

**Comment by DrCoffey** [comment]
Everything seems to work now for me!

![Ep1_1_ZScorePETH_1](https://user-images.githubusercontent.com/39605011/91216443-d1735400-e6ca-11ea-801e-c7596f7be315.jpg)
