### ISSUE TITLE
Loading event files from Neurophotometrics

### ISSUE THREAD

**Issue by flippok** [djamesbarker/pMAT#2]
Hello,

I am trying to load in event files generated by the Neurophotometrics system but seem to be running into issues. I can run the "Plot Trace Data" module and analyze get traces for the signal and control channels as well as normalized delta F/F just fine. However, none of the events are loaded into the GUI and therefore I cannot do any analysis in the PETH module. Is is a formatting issue for how I am feeding in the event data file? It is a .csv with the timestamp in the 1st column of the spreadsheet and the corresponding event identifiers in the 2nd column of the spreadsheet. Thanks for your help. 

Best,

Kyle

**Comment by djamesbarker** [comment]
Hi Kyle,

  There is a typical format.  Column 1 would be a string with event names, Column 2 would be onset timestamps (numbers) and column 3 would be offset timestamps. The 3rd column isn't currently important, so if you only have onset times then you could just copy and paste them twice.

   Try this, or send me your data if you'd like and I will try and help increase the compatibility.  We've been hoping to connect with Neurophotometrics users to see what their raw data looks like and be certain that pMAT works with that system. For example, if the neurophotometrics data is always in the format you just indicated, It would be trivial for me to add an import function specifically for that data.

David
