### ISSUE TITLE
error at MATLAB and application 

### ISSUE THREAD

**Issue by gyujinea5** [djamesbarker/pMAT#8]
Hi, 

I am not familiar with MATLAB. 
So this program is very very helpful to me. 

Today, unfortunately I see some error on MATLAB (with pMAT) and application . 

on MATLAB, I see like this error
----
Processing Block: C:\Users\parkg\Desktop\LepR-Cre\DOB 01.24.21 #13\07.19.21 HFD 6wk non-fasting\07.19.21 HFD 6wk non-fasting\sweet\GP_test1-210719-112959
Unrecognized function or variable 'TDTbin2mat'.

Error in pmat>DataUploadButton_Callback (line 182)
    handles.data=TDTbin2mat([Tank,'\',Block]);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in pmat (line 49)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)pmat('DataUploadButton_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating UIControl Callback.
------

and application I see like this error.
------
unrecognized function or variable 'ctfroot'.
Error in =>runtimeInitializationChecks.m at line 23
-------

How can I fix this errors?

always thanks yo pMAT and yours,

**Comment by djamesbarker** [comment]
Thanks for posting this!

It appears somehow that version 2 GitHub is missing some of the required TDT files. I've re-uploaded these, so re-downloading the file should fix the error.

**Comment by djamesbarker** [comment]
This issue is related to missing TDT Software development kit files. The files have been restored to the directory, but it isn't clear why they were removed or when. Users experiencing this issue should re-download pMAT.
